/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// OpportunitiesApiService OpportunitiesApi service
type OpportunitiesApiService service

type ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest struct {
	ctx context.Context
	ApiService *OpportunitiesApiService
	companyPk string
	createOpportunity *CreateOpportunity
	parentPk *string
	identity *string
}

func (r ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest) CreateOpportunity(createOpportunity CreateOpportunity) ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest {
	r.createOpportunity = &createOpportunity
	return r
}

func (r ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest) ParentPk(parentPk string) ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest {
	r.parentPk = &parentPk
	return r
}

func (r ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest) Identity(identity string) ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest {
	r.identity = &identity
	return r
}

func (r ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.CreateOpportunityApiCompaniesCompanyPkOpportunitiesPostExecute(r)
}

/*
CreateOpportunityApiCompaniesCompanyPkOpportunitiesPost Create Opportunity

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param companyPk
 @return ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest
*/
func (a *OpportunitiesApiService) CreateOpportunityApiCompaniesCompanyPkOpportunitiesPost(ctx context.Context, companyPk string) ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest {
	return ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest{
		ApiService: a,
		ctx: ctx,
		companyPk: companyPk,
	}
}

// Execute executes the request
//  @return interface{}
func (a *OpportunitiesApiService) CreateOpportunityApiCompaniesCompanyPkOpportunitiesPostExecute(r ApiCreateOpportunityApiCompaniesCompanyPkOpportunitiesPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpportunitiesApiService.CreateOpportunityApiCompaniesCompanyPkOpportunitiesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/companies/{company_pk}/opportunities/"
	localVarPath = strings.Replace(localVarPath, "{"+"company_pk"+"}", url.PathEscape(parameterToString(r.companyPk, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createOpportunity == nil {
		return localVarReturnValue, nil, reportError("createOpportunity is required and must be specified")
	}

	if r.parentPk != nil {
		localVarQueryParams.Add("parent_pk", parameterToString(*r.parentPk, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createOpportunity
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetOpportunityDetailsObjectRequest struct {
	ctx context.Context
	ApiService *OpportunitiesApiService
	companyPk string
	opportunityUid string
	parentPk *string
	identity *string
}

func (r ApiGetOpportunityDetailsObjectRequest) ParentPk(parentPk string) ApiGetOpportunityDetailsObjectRequest {
	r.parentPk = &parentPk
	return r
}

func (r ApiGetOpportunityDetailsObjectRequest) Identity(identity string) ApiGetOpportunityDetailsObjectRequest {
	r.identity = &identity
	return r
}

func (r ApiGetOpportunityDetailsObjectRequest) Execute() (*OpportunityDetails, *http.Response, error) {
	return r.ApiService.GetOpportunityDetailsObjectExecute(r)
}

/*
GetOpportunityDetailsObject Get Opportunity Details

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param companyPk
 @param opportunityUid
 @return ApiGetOpportunityDetailsObjectRequest
*/
func (a *OpportunitiesApiService) GetOpportunityDetailsObject(ctx context.Context, companyPk string, opportunityUid string) ApiGetOpportunityDetailsObjectRequest {
	return ApiGetOpportunityDetailsObjectRequest{
		ApiService: a,
		ctx: ctx,
		companyPk: companyPk,
		opportunityUid: opportunityUid,
	}
}

// Execute executes the request
//  @return OpportunityDetails
func (a *OpportunitiesApiService) GetOpportunityDetailsObjectExecute(r ApiGetOpportunityDetailsObjectRequest) (*OpportunityDetails, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OpportunityDetails
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpportunitiesApiService.GetOpportunityDetailsObject")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/companies/{company_pk}/opportunities/{opportunity_uid}/details/"
	localVarPath = strings.Replace(localVarPath, "{"+"company_pk"+"}", url.PathEscape(parameterToString(r.companyPk, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"opportunity_uid"+"}", url.PathEscape(parameterToString(r.opportunityUid, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.parentPk != nil {
		localVarQueryParams.Add("parent_pk", parameterToString(*r.parentPk, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest struct {
	ctx context.Context
	ApiService *OpportunitiesApiService
	companyPk string
	resolution *[]OpportunityResolution
	parentPk *string
	identity *string
}

func (r ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest) Resolution(resolution []OpportunityResolution) ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest {
	r.resolution = &resolution
	return r
}

func (r ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest) ParentPk(parentPk string) ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest {
	r.parentPk = &parentPk
	return r
}

func (r ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest) Identity(identity string) ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest {
	r.identity = &identity
	return r
}

func (r ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest) Execute() ([]Opportunity, *http.Response, error) {
	return r.ApiService.ListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetExecute(r)
}

/*
ListOpportunitiesApiCompaniesCompanyPkOpportunitiesGet List Opportunities

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param companyPk
 @return ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest
*/
func (a *OpportunitiesApiService) ListOpportunitiesApiCompaniesCompanyPkOpportunitiesGet(ctx context.Context, companyPk string) ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest {
	return ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest{
		ApiService: a,
		ctx: ctx,
		companyPk: companyPk,
	}
}

// Execute executes the request
//  @return []Opportunity
func (a *OpportunitiesApiService) ListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetExecute(r ApiListOpportunitiesApiCompaniesCompanyPkOpportunitiesGetRequest) ([]Opportunity, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Opportunity
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpportunitiesApiService.ListOpportunitiesApiCompaniesCompanyPkOpportunitiesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/companies/{company_pk}/opportunities/"
	localVarPath = strings.Replace(localVarPath, "{"+"company_pk"+"}", url.PathEscape(parameterToString(r.companyPk, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.resolution != nil {
		t := *r.resolution
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				localVarQueryParams.Add("resolution", parameterToString(s.Index(i), "multi"))
			}
		} else {
			localVarQueryParams.Add("resolution", parameterToString(t, "multi"))
		}
	}
	if r.parentPk != nil {
		localVarQueryParams.Add("parent_pk", parameterToString(*r.parentPk, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostUpdateOpportunityResolutionRequest struct {
	ctx context.Context
	ApiService *OpportunitiesApiService
	companyPk string
	opportunityUid string
	resolutionUpdate *ResolutionUpdate
	parentPk *string
	identity *string
}

func (r ApiPostUpdateOpportunityResolutionRequest) ResolutionUpdate(resolutionUpdate ResolutionUpdate) ApiPostUpdateOpportunityResolutionRequest {
	r.resolutionUpdate = &resolutionUpdate
	return r
}

func (r ApiPostUpdateOpportunityResolutionRequest) ParentPk(parentPk string) ApiPostUpdateOpportunityResolutionRequest {
	r.parentPk = &parentPk
	return r
}

func (r ApiPostUpdateOpportunityResolutionRequest) Identity(identity string) ApiPostUpdateOpportunityResolutionRequest {
	r.identity = &identity
	return r
}

func (r ApiPostUpdateOpportunityResolutionRequest) Execute() (*http.Response, error) {
	return r.ApiService.PostUpdateOpportunityResolutionExecute(r)
}

/*
PostUpdateOpportunityResolution Post Update Resolution

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param companyPk
 @param opportunityUid
 @return ApiPostUpdateOpportunityResolutionRequest
*/
func (a *OpportunitiesApiService) PostUpdateOpportunityResolution(ctx context.Context, companyPk string, opportunityUid string) ApiPostUpdateOpportunityResolutionRequest {
	return ApiPostUpdateOpportunityResolutionRequest{
		ApiService: a,
		ctx: ctx,
		companyPk: companyPk,
		opportunityUid: opportunityUid,
	}
}

// Execute executes the request
func (a *OpportunitiesApiService) PostUpdateOpportunityResolutionExecute(r ApiPostUpdateOpportunityResolutionRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpportunitiesApiService.PostUpdateOpportunityResolution")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/companies/{company_pk}/opportunities/{opportunity_uid}/"
	localVarPath = strings.Replace(localVarPath, "{"+"company_pk"+"}", url.PathEscape(parameterToString(r.companyPk, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"opportunity_uid"+"}", url.PathEscape(parameterToString(r.opportunityUid, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.resolutionUpdate == nil {
		return nil, reportError("resolutionUpdate is required and must be specified")
	}

	if r.parentPk != nil {
		localVarQueryParams.Add("parent_pk", parameterToString(*r.parentPk, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.resolutionUpdate
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
