/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LeakedPassword struct for LeakedPassword
type LeakedPassword struct {
	Company string `json:"company"`
	Uid string `json:"uid"`
	Type *string `json:"type,omitempty"`
	Group *string `json:"group,omitempty"`
	Entity string `json:"entity"`
	Score *OpportunityScore `json:"score,omitempty"`
	Resolution *OpportunityResolution `json:"resolution,omitempty"`
	Name string `json:"name"`
	PasswordHint string `json:"password_hint"`
	LeakName string `json:"leak_name"`
	LeakYear int32 `json:"leak_year"`
}

// NewLeakedPassword instantiates a new LeakedPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeakedPassword(company string, uid string, entity string, name string, passwordHint string, leakName string, leakYear int32) *LeakedPassword {
	this := LeakedPassword{}
	this.Company = company
	this.Uid = uid
	var type_ string = "leaked_password"
	this.Type = &type_
	var group string = "human_exposure"
	this.Group = &group
	this.Entity = entity
	this.Name = name
	this.PasswordHint = passwordHint
	this.LeakName = leakName
	this.LeakYear = leakYear
	return &this
}

// NewLeakedPasswordWithDefaults instantiates a new LeakedPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeakedPasswordWithDefaults() *LeakedPassword {
	this := LeakedPassword{}
	var type_ string = "leaked_password"
	this.Type = &type_
	var group string = "human_exposure"
	this.Group = &group
	return &this
}

// GetCompany returns the Company field value
func (o *LeakedPassword) GetCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *LeakedPassword) SetCompany(v string) {
	o.Company = v
}

// GetUid returns the Uid field value
func (o *LeakedPassword) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *LeakedPassword) SetUid(v string) {
	o.Uid = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LeakedPassword) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LeakedPassword) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LeakedPassword) SetType(v string) {
	o.Type = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *LeakedPassword) GetGroup() string {
	if o == nil || o.Group == nil {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetGroupOk() (*string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *LeakedPassword) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *LeakedPassword) SetGroup(v string) {
	o.Group = &v
}

// GetEntity returns the Entity field value
func (o *LeakedPassword) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *LeakedPassword) SetEntity(v string) {
	o.Entity = v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *LeakedPassword) GetScore() OpportunityScore {
	if o == nil || o.Score == nil {
		var ret OpportunityScore
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetScoreOk() (*OpportunityScore, bool) {
	if o == nil || o.Score == nil {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *LeakedPassword) HasScore() bool {
	if o != nil && o.Score != nil {
		return true
	}

	return false
}

// SetScore gets a reference to the given OpportunityScore and assigns it to the Score field.
func (o *LeakedPassword) SetScore(v OpportunityScore) {
	o.Score = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *LeakedPassword) GetResolution() OpportunityResolution {
	if o == nil || o.Resolution == nil {
		var ret OpportunityResolution
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetResolutionOk() (*OpportunityResolution, bool) {
	if o == nil || o.Resolution == nil {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *LeakedPassword) HasResolution() bool {
	if o != nil && o.Resolution != nil {
		return true
	}

	return false
}

// SetResolution gets a reference to the given OpportunityResolution and assigns it to the Resolution field.
func (o *LeakedPassword) SetResolution(v OpportunityResolution) {
	o.Resolution = &v
}

// GetName returns the Name field value
func (o *LeakedPassword) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LeakedPassword) SetName(v string) {
	o.Name = v
}

// GetPasswordHint returns the PasswordHint field value
func (o *LeakedPassword) GetPasswordHint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PasswordHint
}

// GetPasswordHintOk returns a tuple with the PasswordHint field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetPasswordHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PasswordHint, true
}

// SetPasswordHint sets field value
func (o *LeakedPassword) SetPasswordHint(v string) {
	o.PasswordHint = v
}

// GetLeakName returns the LeakName field value
func (o *LeakedPassword) GetLeakName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeakName
}

// GetLeakNameOk returns a tuple with the LeakName field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetLeakNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeakName, true
}

// SetLeakName sets field value
func (o *LeakedPassword) SetLeakName(v string) {
	o.LeakName = v
}

// GetLeakYear returns the LeakYear field value
func (o *LeakedPassword) GetLeakYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LeakYear
}

// GetLeakYearOk returns a tuple with the LeakYear field value
// and a boolean to check if the value has been set.
func (o *LeakedPassword) GetLeakYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeakYear, true
}

// SetLeakYear sets field value
func (o *LeakedPassword) SetLeakYear(v int32) {
	o.LeakYear = v
}

func (o LeakedPassword) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["company"] = o.Company
	}
	if true {
		toSerialize["uid"] = o.Uid
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	if true {
		toSerialize["entity"] = o.Entity
	}
	if o.Score != nil {
		toSerialize["score"] = o.Score
	}
	if o.Resolution != nil {
		toSerialize["resolution"] = o.Resolution
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["password_hint"] = o.PasswordHint
	}
	if true {
		toSerialize["leak_name"] = o.LeakName
	}
	if true {
		toSerialize["leak_year"] = o.LeakYear
	}
	return json.Marshal(toSerialize)
}

type NullableLeakedPassword struct {
	value *LeakedPassword
	isSet bool
}

func (v NullableLeakedPassword) Get() *LeakedPassword {
	return v.value
}

func (v *NullableLeakedPassword) Set(val *LeakedPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableLeakedPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableLeakedPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeakedPassword(val *LeakedPassword) *NullableLeakedPassword {
	return &NullableLeakedPassword{value: val, isSet: true}
}

func (v NullableLeakedPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeakedPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


