/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PaginatedEntityCollectionMetaEntity struct for PaginatedEntityCollectionMetaEntity
type PaginatedEntityCollectionMetaEntity struct {
	Entities []MetaEntity `json:"entities"`
	Marker *string `json:"marker,omitempty"`
}

// NewPaginatedEntityCollectionMetaEntity instantiates a new PaginatedEntityCollectionMetaEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedEntityCollectionMetaEntity(entities []MetaEntity) *PaginatedEntityCollectionMetaEntity {
	this := PaginatedEntityCollectionMetaEntity{}
	this.Entities = entities
	return &this
}

// NewPaginatedEntityCollectionMetaEntityWithDefaults instantiates a new PaginatedEntityCollectionMetaEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedEntityCollectionMetaEntityWithDefaults() *PaginatedEntityCollectionMetaEntity {
	this := PaginatedEntityCollectionMetaEntity{}
	return &this
}

// GetEntities returns the Entities field value
func (o *PaginatedEntityCollectionMetaEntity) GetEntities() []MetaEntity {
	if o == nil {
		var ret []MetaEntity
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *PaginatedEntityCollectionMetaEntity) GetEntitiesOk() ([]MetaEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *PaginatedEntityCollectionMetaEntity) SetEntities(v []MetaEntity) {
	o.Entities = v
}

// GetMarker returns the Marker field value if set, zero value otherwise.
func (o *PaginatedEntityCollectionMetaEntity) GetMarker() string {
	if o == nil || o.Marker == nil {
		var ret string
		return ret
	}
	return *o.Marker
}

// GetMarkerOk returns a tuple with the Marker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedEntityCollectionMetaEntity) GetMarkerOk() (*string, bool) {
	if o == nil || o.Marker == nil {
		return nil, false
	}
	return o.Marker, true
}

// HasMarker returns a boolean if a field has been set.
func (o *PaginatedEntityCollectionMetaEntity) HasMarker() bool {
	if o != nil && o.Marker != nil {
		return true
	}

	return false
}

// SetMarker gets a reference to the given string and assigns it to the Marker field.
func (o *PaginatedEntityCollectionMetaEntity) SetMarker(v string) {
	o.Marker = &v
}

func (o PaginatedEntityCollectionMetaEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entities"] = o.Entities
	}
	if o.Marker != nil {
		toSerialize["marker"] = o.Marker
	}
	return json.Marshal(toSerialize)
}

type NullablePaginatedEntityCollectionMetaEntity struct {
	value *PaginatedEntityCollectionMetaEntity
	isSet bool
}

func (v NullablePaginatedEntityCollectionMetaEntity) Get() *PaginatedEntityCollectionMetaEntity {
	return v.value
}

func (v *NullablePaginatedEntityCollectionMetaEntity) Set(val *PaginatedEntityCollectionMetaEntity) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedEntityCollectionMetaEntity) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedEntityCollectionMetaEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedEntityCollectionMetaEntity(val *PaginatedEntityCollectionMetaEntity) *NullablePaginatedEntityCollectionMetaEntity {
	return &NullablePaginatedEntityCollectionMetaEntity{value: val, isSet: true}
}

func (v NullablePaginatedEntityCollectionMetaEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedEntityCollectionMetaEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


