/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SuspiciousDomain struct for SuspiciousDomain
type SuspiciousDomain struct {
	Company string `json:"company"`
	Uid string `json:"uid"`
	Type *string `json:"type,omitempty"`
	Group *string `json:"group,omitempty"`
	Entity string `json:"entity"`
	Score *OpportunityScore `json:"score,omitempty"`
	Resolution *OpportunityResolution `json:"resolution,omitempty"`
	Name string `json:"name"`
	ScoreDetails map[string][]IndividualScore `json:"score_details"`
}

// NewSuspiciousDomain instantiates a new SuspiciousDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuspiciousDomain(company string, uid string, entity string, name string, scoreDetails map[string][]IndividualScore) *SuspiciousDomain {
	this := SuspiciousDomain{}
	this.Company = company
	this.Uid = uid
	var type_ string = "suspicious_domain"
	this.Type = &type_
	var group string = "domains"
	this.Group = &group
	this.Entity = entity
	this.Name = name
	this.ScoreDetails = scoreDetails
	return &this
}

// NewSuspiciousDomainWithDefaults instantiates a new SuspiciousDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuspiciousDomainWithDefaults() *SuspiciousDomain {
	this := SuspiciousDomain{}
	var type_ string = "suspicious_domain"
	this.Type = &type_
	var group string = "domains"
	this.Group = &group
	return &this
}

// GetCompany returns the Company field value
func (o *SuspiciousDomain) GetCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *SuspiciousDomain) SetCompany(v string) {
	o.Company = v
}

// GetUid returns the Uid field value
func (o *SuspiciousDomain) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *SuspiciousDomain) SetUid(v string) {
	o.Uid = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SuspiciousDomain) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SuspiciousDomain) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SuspiciousDomain) SetType(v string) {
	o.Type = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *SuspiciousDomain) GetGroup() string {
	if o == nil || o.Group == nil {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetGroupOk() (*string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *SuspiciousDomain) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *SuspiciousDomain) SetGroup(v string) {
	o.Group = &v
}

// GetEntity returns the Entity field value
func (o *SuspiciousDomain) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *SuspiciousDomain) SetEntity(v string) {
	o.Entity = v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *SuspiciousDomain) GetScore() OpportunityScore {
	if o == nil || o.Score == nil {
		var ret OpportunityScore
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetScoreOk() (*OpportunityScore, bool) {
	if o == nil || o.Score == nil {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *SuspiciousDomain) HasScore() bool {
	if o != nil && o.Score != nil {
		return true
	}

	return false
}

// SetScore gets a reference to the given OpportunityScore and assigns it to the Score field.
func (o *SuspiciousDomain) SetScore(v OpportunityScore) {
	o.Score = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *SuspiciousDomain) GetResolution() OpportunityResolution {
	if o == nil || o.Resolution == nil {
		var ret OpportunityResolution
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetResolutionOk() (*OpportunityResolution, bool) {
	if o == nil || o.Resolution == nil {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *SuspiciousDomain) HasResolution() bool {
	if o != nil && o.Resolution != nil {
		return true
	}

	return false
}

// SetResolution gets a reference to the given OpportunityResolution and assigns it to the Resolution field.
func (o *SuspiciousDomain) SetResolution(v OpportunityResolution) {
	o.Resolution = &v
}

// GetName returns the Name field value
func (o *SuspiciousDomain) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SuspiciousDomain) SetName(v string) {
	o.Name = v
}

// GetScoreDetails returns the ScoreDetails field value
func (o *SuspiciousDomain) GetScoreDetails() map[string][]IndividualScore {
	if o == nil {
		var ret map[string][]IndividualScore
		return ret
	}

	return o.ScoreDetails
}

// GetScoreDetailsOk returns a tuple with the ScoreDetails field value
// and a boolean to check if the value has been set.
func (o *SuspiciousDomain) GetScoreDetailsOk() (*map[string][]IndividualScore, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoreDetails, true
}

// SetScoreDetails sets field value
func (o *SuspiciousDomain) SetScoreDetails(v map[string][]IndividualScore) {
	o.ScoreDetails = v
}

func (o SuspiciousDomain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["company"] = o.Company
	}
	if true {
		toSerialize["uid"] = o.Uid
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	if true {
		toSerialize["entity"] = o.Entity
	}
	if o.Score != nil {
		toSerialize["score"] = o.Score
	}
	if o.Resolution != nil {
		toSerialize["resolution"] = o.Resolution
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["score_details"] = o.ScoreDetails
	}
	return json.Marshal(toSerialize)
}

type NullableSuspiciousDomain struct {
	value *SuspiciousDomain
	isSet bool
}

func (v NullableSuspiciousDomain) Get() *SuspiciousDomain {
	return v.value
}

func (v *NullableSuspiciousDomain) Set(val *SuspiciousDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableSuspiciousDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableSuspiciousDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuspiciousDomain(val *SuspiciousDomain) *NullableSuspiciousDomain {
	return &NullableSuspiciousDomain{value: val, isSet: true}
}

func (v NullableSuspiciousDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuspiciousDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


