/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MFASetupChallengeRequest struct for MFASetupChallengeRequest
type MFASetupChallengeRequest struct {
	Token string `json:"token"`
}

// NewMFASetupChallengeRequest instantiates a new MFASetupChallengeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFASetupChallengeRequest(token string) *MFASetupChallengeRequest {
	this := MFASetupChallengeRequest{}
	this.Token = token
	return &this
}

// NewMFASetupChallengeRequestWithDefaults instantiates a new MFASetupChallengeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFASetupChallengeRequestWithDefaults() *MFASetupChallengeRequest {
	this := MFASetupChallengeRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *MFASetupChallengeRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *MFASetupChallengeRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *MFASetupChallengeRequest) SetToken(v string) {
	o.Token = v
}

func (o MFASetupChallengeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableMFASetupChallengeRequest struct {
	value *MFASetupChallengeRequest
	isSet bool
}

func (v NullableMFASetupChallengeRequest) Get() *MFASetupChallengeRequest {
	return v.value
}

func (v *NullableMFASetupChallengeRequest) Set(val *MFASetupChallengeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMFASetupChallengeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMFASetupChallengeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFASetupChallengeRequest(val *MFASetupChallengeRequest) *NullableMFASetupChallengeRequest {
	return &NullableMFASetupChallengeRequest{value: val, isSet: true}
}

func (v NullableMFASetupChallengeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFASetupChallengeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


