/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SubdomainEnumerationScan struct for SubdomainEnumerationScan
type SubdomainEnumerationScan struct {
	SourceLookup string `json:"source_lookup"`
	Type *string `json:"type,omitempty"`
}

// NewSubdomainEnumerationScan instantiates a new SubdomainEnumerationScan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubdomainEnumerationScan(sourceLookup string) *SubdomainEnumerationScan {
	this := SubdomainEnumerationScan{}
	this.SourceLookup = sourceLookup
	var type_ string = "scan.subdomain"
	this.Type = &type_
	return &this
}

// NewSubdomainEnumerationScanWithDefaults instantiates a new SubdomainEnumerationScan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubdomainEnumerationScanWithDefaults() *SubdomainEnumerationScan {
	this := SubdomainEnumerationScan{}
	var type_ string = "scan.subdomain"
	this.Type = &type_
	return &this
}

// GetSourceLookup returns the SourceLookup field value
func (o *SubdomainEnumerationScan) GetSourceLookup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceLookup
}

// GetSourceLookupOk returns a tuple with the SourceLookup field value
// and a boolean to check if the value has been set.
func (o *SubdomainEnumerationScan) GetSourceLookupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceLookup, true
}

// SetSourceLookup sets field value
func (o *SubdomainEnumerationScan) SetSourceLookup(v string) {
	o.SourceLookup = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SubdomainEnumerationScan) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubdomainEnumerationScan) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SubdomainEnumerationScan) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SubdomainEnumerationScan) SetType(v string) {
	o.Type = &v
}

func (o SubdomainEnumerationScan) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["source_lookup"] = o.SourceLookup
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableSubdomainEnumerationScan struct {
	value *SubdomainEnumerationScan
	isSet bool
}

func (v NullableSubdomainEnumerationScan) Get() *SubdomainEnumerationScan {
	return v.value
}

func (v *NullableSubdomainEnumerationScan) Set(val *SubdomainEnumerationScan) {
	v.value = val
	v.isSet = true
}

func (v NullableSubdomainEnumerationScan) IsSet() bool {
	return v.isSet
}

func (v *NullableSubdomainEnumerationScan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubdomainEnumerationScan(val *SubdomainEnumerationScan) *NullableSubdomainEnumerationScan {
	return &NullableSubdomainEnumerationScan{value: val, isSet: true}
}

func (v NullableSubdomainEnumerationScan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubdomainEnumerationScan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


