/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EmailBody struct for EmailBody
type EmailBody struct {
	Email string `json:"email"`
}

// NewEmailBody instantiates a new EmailBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailBody(email string) *EmailBody {
	this := EmailBody{}
	this.Email = email
	return &this
}

// NewEmailBodyWithDefaults instantiates a new EmailBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailBodyWithDefaults() *EmailBody {
	this := EmailBody{}
	return &this
}

// GetEmail returns the Email field value
func (o *EmailBody) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailBody) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailBody) SetEmail(v string) {
	o.Email = v
}

func (o EmailBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableEmailBody struct {
	value *EmailBody
	isSet bool
}

func (v NullableEmailBody) Get() *EmailBody {
	return v.value
}

func (v *NullableEmailBody) Set(val *EmailBody) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailBody) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailBody(val *EmailBody) *NullableEmailBody {
	return &NullableEmailBody{value: val, isSet: true}
}

func (v NullableEmailBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


