/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IntegrationWithAssets struct for IntegrationWithAssets
type IntegrationWithAssets struct {
	Assets PaginatedEntityCollectionMetaEntity `json:"assets"`
	Entity IntegrationEntity `json:"entity"`
}

// NewIntegrationWithAssets instantiates a new IntegrationWithAssets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationWithAssets(assets PaginatedEntityCollectionMetaEntity, entity IntegrationEntity) *IntegrationWithAssets {
	this := IntegrationWithAssets{}
	this.Assets = assets
	this.Entity = entity
	return &this
}

// NewIntegrationWithAssetsWithDefaults instantiates a new IntegrationWithAssets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationWithAssetsWithDefaults() *IntegrationWithAssets {
	this := IntegrationWithAssets{}
	return &this
}

// GetAssets returns the Assets field value
func (o *IntegrationWithAssets) GetAssets() PaginatedEntityCollectionMetaEntity {
	if o == nil {
		var ret PaginatedEntityCollectionMetaEntity
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *IntegrationWithAssets) GetAssetsOk() (*PaginatedEntityCollectionMetaEntity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assets, true
}

// SetAssets sets field value
func (o *IntegrationWithAssets) SetAssets(v PaginatedEntityCollectionMetaEntity) {
	o.Assets = v
}

// GetEntity returns the Entity field value
func (o *IntegrationWithAssets) GetEntity() IntegrationEntity {
	if o == nil {
		var ret IntegrationEntity
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *IntegrationWithAssets) GetEntityOk() (*IntegrationEntity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *IntegrationWithAssets) SetEntity(v IntegrationEntity) {
	o.Entity = v
}

func (o IntegrationWithAssets) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["assets"] = o.Assets
	}
	if true {
		toSerialize["entity"] = o.Entity
	}
	return json.Marshal(toSerialize)
}

type NullableIntegrationWithAssets struct {
	value *IntegrationWithAssets
	isSet bool
}

func (v NullableIntegrationWithAssets) Get() *IntegrationWithAssets {
	return v.value
}

func (v *NullableIntegrationWithAssets) Set(val *IntegrationWithAssets) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationWithAssets) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationWithAssets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationWithAssets(val *IntegrationWithAssets) *NullableIntegrationWithAssets {
	return &NullableIntegrationWithAssets{value: val, isSet: true}
}

func (v NullableIntegrationWithAssets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationWithAssets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


