/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AmassEnum struct for AmassEnum
type AmassEnum struct {
	SourceLookup string `json:"source_lookup"`
	Type *string `json:"type,omitempty"`
}

// NewAmassEnum instantiates a new AmassEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmassEnum(sourceLookup string) *AmassEnum {
	this := AmassEnum{}
	this.SourceLookup = sourceLookup
	var type_ string = "scan.amass-enum"
	this.Type = &type_
	return &this
}

// NewAmassEnumWithDefaults instantiates a new AmassEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmassEnumWithDefaults() *AmassEnum {
	this := AmassEnum{}
	var type_ string = "scan.amass-enum"
	this.Type = &type_
	return &this
}

// GetSourceLookup returns the SourceLookup field value
func (o *AmassEnum) GetSourceLookup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceLookup
}

// GetSourceLookupOk returns a tuple with the SourceLookup field value
// and a boolean to check if the value has been set.
func (o *AmassEnum) GetSourceLookupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceLookup, true
}

// SetSourceLookup sets field value
func (o *AmassEnum) SetSourceLookup(v string) {
	o.SourceLookup = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AmassEnum) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmassEnum) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AmassEnum) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AmassEnum) SetType(v string) {
	o.Type = &v
}

func (o AmassEnum) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["source_lookup"] = o.SourceLookup
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableAmassEnum struct {
	value *AmassEnum
	isSet bool
}

func (v NullableAmassEnum) Get() *AmassEnum {
	return v.value
}

func (v *NullableAmassEnum) Set(val *AmassEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAmassEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAmassEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmassEnum(val *AmassEnum) *NullableAmassEnum {
	return &NullableAmassEnum{value: val, isSet: true}
}

func (v NullableAmassEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmassEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


