/*
Web backend for Vikingr

The main api for Vikingr

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PaginatedEntityCollectionSubdomainEntity struct for PaginatedEntityCollectionSubdomainEntity
type PaginatedEntityCollectionSubdomainEntity struct {
	Entities []SubdomainEntity `json:"entities"`
	Marker *string `json:"marker,omitempty"`
}

// NewPaginatedEntityCollectionSubdomainEntity instantiates a new PaginatedEntityCollectionSubdomainEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedEntityCollectionSubdomainEntity(entities []SubdomainEntity) *PaginatedEntityCollectionSubdomainEntity {
	this := PaginatedEntityCollectionSubdomainEntity{}
	this.Entities = entities
	return &this
}

// NewPaginatedEntityCollectionSubdomainEntityWithDefaults instantiates a new PaginatedEntityCollectionSubdomainEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedEntityCollectionSubdomainEntityWithDefaults() *PaginatedEntityCollectionSubdomainEntity {
	this := PaginatedEntityCollectionSubdomainEntity{}
	return &this
}

// GetEntities returns the Entities field value
func (o *PaginatedEntityCollectionSubdomainEntity) GetEntities() []SubdomainEntity {
	if o == nil {
		var ret []SubdomainEntity
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *PaginatedEntityCollectionSubdomainEntity) GetEntitiesOk() ([]SubdomainEntity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *PaginatedEntityCollectionSubdomainEntity) SetEntities(v []SubdomainEntity) {
	o.Entities = v
}

// GetMarker returns the Marker field value if set, zero value otherwise.
func (o *PaginatedEntityCollectionSubdomainEntity) GetMarker() string {
	if o == nil || o.Marker == nil {
		var ret string
		return ret
	}
	return *o.Marker
}

// GetMarkerOk returns a tuple with the Marker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedEntityCollectionSubdomainEntity) GetMarkerOk() (*string, bool) {
	if o == nil || o.Marker == nil {
		return nil, false
	}
	return o.Marker, true
}

// HasMarker returns a boolean if a field has been set.
func (o *PaginatedEntityCollectionSubdomainEntity) HasMarker() bool {
	if o != nil && o.Marker != nil {
		return true
	}

	return false
}

// SetMarker gets a reference to the given string and assigns it to the Marker field.
func (o *PaginatedEntityCollectionSubdomainEntity) SetMarker(v string) {
	o.Marker = &v
}

func (o PaginatedEntityCollectionSubdomainEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entities"] = o.Entities
	}
	if o.Marker != nil {
		toSerialize["marker"] = o.Marker
	}
	return json.Marshal(toSerialize)
}

type NullablePaginatedEntityCollectionSubdomainEntity struct {
	value *PaginatedEntityCollectionSubdomainEntity
	isSet bool
}

func (v NullablePaginatedEntityCollectionSubdomainEntity) Get() *PaginatedEntityCollectionSubdomainEntity {
	return v.value
}

func (v *NullablePaginatedEntityCollectionSubdomainEntity) Set(val *PaginatedEntityCollectionSubdomainEntity) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedEntityCollectionSubdomainEntity) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedEntityCollectionSubdomainEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedEntityCollectionSubdomainEntity(val *PaginatedEntityCollectionSubdomainEntity) *NullablePaginatedEntityCollectionSubdomainEntity {
	return &NullablePaginatedEntityCollectionSubdomainEntity{value: val, isSet: true}
}

func (v NullablePaginatedEntityCollectionSubdomainEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedEntityCollectionSubdomainEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


