name: Build & Test

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  GOPATH: "/home/runner/go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go get -v .

      - name: Generate
        run: |
          env | grep GO
          ls ~/go
          echo "bin contents"
          ls ~/go/bin
          echo "--------"
          echo $PATH
          go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
